baseURL = "https://jon4hz.io/"
languageCode = "en-us"
title = "jon4hz.io"
theme = "hello-friend-ng"

enableRobotsTXT = true

[author]
  name = "Jonah"

[languages]
  [languages.en]
    title = "jonahz.io"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

    [languages.en.params.logo]
      logoText = "hello friend"
      logoHomeLink = "/"

[params]
 
  enableThemeToggle = true
 
  [params.footer]
    trademark = true
    rss = false
    copyright = true
    author = true
  
  [[params.social]]
    name = "github"
    url = "https://github.com/jon4hz"
  [[params.social]]
    name = "email"
    url = "mailto:me@jon4hz.io"
  
[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"
  
[[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"