baseURL = "https://jon4hz.io/"
languageCode = "en-us"
title = "jon4hz.io"
theme = "hello-friend-ng"

enableRobotsTXT = true

[author]
  name = "Jonah"

[languages]
  [languages.en]
    title = "jon4hz.io"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

    [languages.en.params.logo]
      logoText = "$ ./hello_friend"
      logoHomeLink = "/"

[params]
  enableThemeToggle = true
  homeSubtitle = "I like computers, decentralization and blockchain"
 
  [params.footer]
    trademark = true
    rss = false
    copyright = true
    author = true
  
  [[params.social]]
    name = "github"
    url = "https://github.com/jon4hz"

  [[params.social]]
    name = "email"
    url = "mailto:me@jon4hz.io"

  [[params.social]]
    name = "telegram"
    url = "https://t.me/jon4hz"
  
[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"
  
[[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
